import java.util.ArrayList;
import java.util.HashSet;

public class Component {
    int key;
    String repo_name;
    int size;
    int diameter;
    float density;
    HashSet<String> list_of_authors;
    int comment_count;
    String component_url;
    int repo_contributors;
    ArrayList<String> list_of_nodes;
    
    public Component(int key, String repo_name, int size, int diameter, float density, HashSet<String> list_of_authors, String component_url, int comment_count, int repo_contributors, ArrayList<String> list_of_nodes) {
        this.key = key;
        this.repo_name = repo_name;
        this.size = size;
        this.diameter = diameter;
        this.density = density;
        this.list_of_authors = list_of_authors;
        this.comment_count = comment_count;
        this.component_url = component_url;
        this.repo_contributors = repo_contributors;
        this.list_of_nodes = list_of_nodes;
    }

    @Override
    public String toString() {
        return this.key + " " + this.repo_name + " " + this.size + " " + this.density + " " + this.diameter;
    }

    @Override
    public int hashCode() {
        // Key is a unique key field from the CSV files
        return key;
    }

    @Override
    public boolean equals(Object obj) {
        // Auto generated by VSCode
        // Since key is a unique key field from the CSV files
        // This is acceptable
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Component other = (Component) obj;
        if (key != other.key)
            return false;
        return true;
    }

    
}
